---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 13:31
---

require("test")



for i=1,5 do
    print(i)
end

require("dumpTable")

local tt = {}
table.insert(tt,"d")
tt[1212] = 23
tt["33dd"]= "ff"

printTable(tt)
--table.remove(tt,1)
tt["33dd"] = nil
tt[1212] = nil
tt[1] = nil

printTable(tt)


print("----------------------------------------")


math.randomseed(os.time())
print(math.random(3))

print("----------------------------------------")

print(os.time())
print(os.time({year =2916, month = 11, day =23, hour =17, min =17, sec = 00}))

