---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/19 16:20
---


text = { }
text.defaultValue = { size = 14, content = "hello" }
text.mt = { }  -- 创建元表

function text.new( a )
    setmetatable( a, text.mt )
    return a
end

text.mt.__index = function( tb, key )
    return text.defaultValue[key]
end

local x = text.new{ content = "bye" }
print( x.size )   --> 14