---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/4/11 15:45
---


package.path = package.path .. ';protobuf/?.lua'
package.cpath = package.cpath .. ';protobuf/?.so'


require ("protobuf.protobuf")


require("Protocol.protocol_test")