---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/4/11 15:45
---


package.path = package.path .. ';protobuf/?.lua'
package.cpath = package.cpath .. ';protobuf/?.dll'

--local a = package.loadlib("pb.dll", "luaopen_pb");
--a()
--require ("protobuf.protobuf")
package.path = "./Protocol/?.lua;"..package.path
package.path = "./Protocol/build/?.lua;"..package.path

--require("protocol_test")



require("metaTable")
print("ddd")

function ss()
    zsw = function(name)
        print("zz", name)
    end
end

ss()

zsw1 = zsw
zsw()
zsw1(1)

require("func")
require("test2")