---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/4/11 15:45
---

print("3333333333")

--
--function double2(inss)
--    return inss*100
--end
--
--print(double2(9))