---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/12 15:56
---
print("fffffffffffffffffffffffffffffffffffff")


--package.path = package.path .. ';protobuf/?.lua'
--package.cpath = package.cpath .. ';protobuf/?.so'

local user_pb = require('Protocol.build.user_pb')
--local user_pb = require('user_pb')


print("fffffffffffffffffffffffffffffffffffff")


local person= user_pb.Friend()
person.name = "zsw"
person.adress = "zsw adress"

local data = person:SerializeToString()

local msg = user_pb.Friend()
msg:ParseFromString(data)
print(msg)